// <auto-generated>
// Written by tools/bindgen.nx from native/plugin/plugin.odin. Do not edit; rerun the build.
// </auto-generated>
#if !UNITY_WEBGL   // no native library in the browser: SimCore stands in for the Odin core there
using System;
using System.Runtime.InteropServices;

namespace PointOfOrigin.Native
{
    /// <summary>P/Invoke surface of origin_sim.dll, the Odin simulation core.</summary>
    public static class PoNative
    {
        public const string Lib = "origin_sim";

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern int po_version();

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr po_create(int w, int h);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern void po_destroy(IntPtr g);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern int po_width(IntPtr g);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern int po_height(IntPtr g);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern void po_set_rule(IntPtr g, uint birth, uint survive);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern void po_clear_life(IntPtr g);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern void po_clear_all(IntPtr g);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern void po_set_cell(IntPtr g, int x, int y, byte v);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern byte po_get_cell(IntPtr g, int x, int y);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern void po_load(IntPtr g, byte[] cells, int count);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern int po_copy_cells(IntPtr g, byte[] dst, int count);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern int po_copy_ages(IntPtr g, ushort[] dst, int count);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern int po_step(IntPtr g, int n);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern int po_generation(IntPtr g);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern int po_alive_count(IntPtr g);

        [DllImport(Lib, CallingConvention = CallingConvention.Cdecl)]
        public static extern float po_compare(IntPtr g, byte[] target, int count);

    }
}
#endif
